version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "handler"
        Alias: "query"
        CurrentVersion: "1"
        TargetVersion: "2"
#Hooks:
#  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
#  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"