service: icarus
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: icarus-serverless
functions:
  query:
    handler: handler.query
    events:
      - http: # http object contents have to be indented two tabstops below
          path: query
          method: get